// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  translation: {
    languageEnglish: 'English'
    languageSpanish: 'Spanish'
  }
  ui: {
    notFoundDescription: "The page you're looking for doesn't exist."
    notFoundTitle: '404 - Not Found'
  }
}

export default Resources
